### ISSUE TITLE
Замечания по работе№1

### ISSUE THREAD

**Issue by AndriiLitvin** [RSRaven/RSRaven.github.io#1]
Визуально:
http://joxi.ru/Dr8ERJ6FGd9Gm6
1)Нет серого фона.
2)Нет бордер радиус и тени на блоке с визиткой
3)Цвет бордера
4)Ширина картинки, подгони чтоб было как на превьюшке.

Код:
1) На теги лучше css не натравливать, делать через классы.

**Comment by RSRaven** [comment]
Поправил.
1. Фон есть.
2. Бордер радиус есть. Тень вокруг всего враппера.
3. Цвет поправил.
4. Ширину поменял.
5. Пределал css.

**Comment by AndriiLitvin** [comment]
Зачет
