### ISSUE TITLE
Замечания по экзамену 7-9

### ISSUE THREAD

**Issue by AndriiLitvin** [RSRaven/RSRaven.github.io#6]
Все норм. ну есть замечания.
 чтоб я засчитал экзамен нужно сделать 9 работу
-
+ по всему макету text-shadow
+  проверяю на мозиле

Экран 960 http://joxi.ru/RmzkEJqFWWdLp2
-
1)там с лого что то не то
2)3) это активный элемент слайдера
4) тут не нужно спрайтами делать. так как если придется  менять спрайт. лучше сделать картинками. а если сделать ховер эфект то есть css фильтры. хотя смотриться норм.
на остальных экранах тоже самое

**Comment by RSRaven** [comment]
1. С лого - это да, разбираюсь, как его сделать. Ни ff, ни ie не поддерживают background-clip: text;  Пока склоняюсь к тому, чтобы его просто в фиолетовый закрасить. Будет почти как на макете.
2-3. Я понимаю, что это элемент слайдера, но что с ним делать? Олег сказал, сверстать меню. Это я сделал.
4. Поменяется какая-нибудь компания - придётся переделывать спрайт, понятно. Переделать в картинки?

**Comment by AndriiLitvin** [comment]
>2-3) Я понимаю, что это элемент слайдера, но что с ним делать? Олег сказал, сверстать меню. Это я сделал.

просто добавь класс active и ему добавь свойства активного элемента как на макете

>4) Поменяется какая-нибудь компания - придётся переделывать спрайт, понятно. Переделать в картинки?

да переделай так коректней будет. как ни как это экзамен

**Comment by RSRaven** [comment]
1) С логотипом разобрался - теперь работает как надо.
2-3) Добавил active.
4) Теперь картинки. С ховерами :)
5) Добавил text-shadow, где не хватало.

**Comment by AndriiLitvin** [comment]
экран 480 http://joxi.ru/brR6zPluQQZ8lr
-
1) Убери последнему элементу марджин райт

**Comment by RSRaven** [comment]
Не досмотрел. Я его убрал, только не у **li**, а у **a**... Исправил :)

**Comment by AndriiLitvin** [comment]
ЗАЧЕТ
